name: Build EXE with PyInstaller and include version in name

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Extract version from tag
      id: vars
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole --icon=resources/img/pincab.ico pincab-manager.py ^
          --add-data "libvlccore.dll;." ^
          --add-data "libvlc.dll;." ^
          --add-data "plugins;plugins" ^
          --add-data "resources;resources" ^
          --add-data "binaries;binaries" ^
          --add-data "CHANGELOG;."

    - name: Rename EXE with version
      run: |
        ren dist\pincab-manager.exe pincab-manager-v%VERSION%.exe

    - name: Upload executable to release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/pincab-manager-v${{ env.VERSION }}.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
