name: Create Release from CHANGELOG version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Extract version from CHANGELOG
        id: extract_version
        run: |
          first_line=$(head -n 1 CHANGELOG)
          echo "First line: $first_line"
          version=$(echo $first_line | awk '{print $1}')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Merge develop into main
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin main
          git checkout main
          git merge develop --no-ff -m "Merge develop into main for release"

      - name: Create tag with extracted version
        run: |
          git tag $VERSION
          git push origin main --tags
